# Generated by Django 4.0.6 on 2023-03-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='-', max_length=200)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='SemestreAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_semestre', models.DateField()),
                ('fecha_culminacion_semestre', models.DateField()),
                ('fecha_limite_40porciento', models.DateField()),
                ('fecha_inicio_habilitacion', models.DateField()),
                ('fecha_culminacion_habilitacion', models.DateField()),
                ('fecha_cierre_periodo_academico', models.DateField()),
            ],
            options={
                'verbose_name': 'Semestre Academico',
                'verbose_name_plural': 'Semestre Academico',
            },
        ),
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_matricula', models.DateField()),
                ('fecha_final_matricula', models.DateField()),
                ('fecha_inicio_ajustes', models.DateField()),
                ('fecha_final_ajustes', models.DateField()),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPeriodo.facultad')),
            ],
            options={
                'verbose_name': 'Calendario Academico',
                'verbose_name_plural': 'Calendario Academico',
            },
        ),
    ]
